blank_issues_enabled: false
contact_links:
  - name: Security Issue
    url: https://github.com/DollhouseMCP/collection/security/advisories/new
    about: Please report security vulnerabilities here
  - name: DollhouseMCP Server Issues
    url: https://github.com/DollhouseMCP/mcp-server/issues
    about: For issues with the MCP server itself
  - name: Community Chat
    url: https://github.com/DollhouseMCP/collection/discussions
    about: Ask questions and discuss with the community