name: Feature Request
description: Suggest a new feature for the DollhouseMCP Collection
title: "[Feature]: "
labels: ["type: enhancement", "collection-repo"]
projects: ["DollhouseMCP/1"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below.

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: What area would this feature affect?
      options:
        - New Content Type
        - Validation Enhancement
        - Security Feature
        - CI/CD Improvement
        - Documentation
        - User Experience
        - Developer Tools
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the issue or limitation you're facing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How would this benefit users of the Collection?
      placeholder: |
        - Benefit 1
        - Benefit 2
        - Benefit 3

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Critical for my use case

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this feature