name: Build Collection Index

on:
  push:
    paths:
      - 'library/**/*.md'
      - 'scripts/build-collection-index.ts'
      - '.github/workflows/build-collection-index.yml'
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'library/**/*.md'
      - 'scripts/build-collection-index.ts'
      - '.github/workflows/build-collection-index.yml'
  workflow_dispatch:

jobs:
  build-index:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Create public directory
        run: mkdir -p public

      - name: Build collection index
        run: node dist/scripts/build-collection-index.js

      - name: Verify index was created
        run: |
          if [ ! -f "public/collection-index.json" ]; then
            echo "Error: collection-index.json was not created"
            exit 1
          fi
          echo "Index file size: $(wc -c < public/collection-index.json) bytes"
          echo "Element count: $(jq '.total_elements' public/collection-index.json)"

      - name: Check for changes
        id: git-check
        run: |
          git add public/collection-index.json
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      # Disabled: Cannot push to protected branch
      # The index is still built and uploaded as an artifact
      # TODO: Create PR instead of direct push for protected branches
      # - name: Commit updated index
      #   if: steps.git-check.outputs.changed == 'true' && github.event_name == 'push'

      - name: Comment on PR with index stats
        if: steps.git-check.outputs.changed == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const indexData = JSON.parse(fs.readFileSync('public/collection-index.json', 'utf8'));
            
            const comment = `## Collection Index Updated 🤖
            
            The collection index has been automatically updated:
            
            - **Total Elements**: ${indexData.total_elements}
            - **Build Time**: ${indexData.metadata.build_time_ms}ms
            - **Categories**: ${Object.keys(indexData.index).length}
            - **Generated**: ${indexData.generated}
            
            ### Category Breakdown:
            ${Object.entries(indexData.index).map(([category, items]) => 
              `- **${category}**: ${items.length} items`
            ).join('\n')}
            
            The updated index will be automatically committed when this PR is merged.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Upload index as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: collection-index
          path: public/collection-index.json
          retention-days: 30