name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
  issues:
    types: [opened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  claude-code-review:
    name: Claude Code Review
    runs-on: ubuntu-latest
    
    steps:
      - name: Claude Code Review
        uses: anthropics/claude-code-action@v1
        with:
          # GitHub App authentication - no API key needed
          # The app should be installed on the repository
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Model selection (optional)
          model: "claude-3-5-sonnet-20241022"
          
          # Maximum iterations for multi-turn conversations
          max-iterations: 3
          
          # Temperature for responses (0-1)
          temperature: 0.7
          
          # Maximum tokens per response
          max-tokens: 4096
          
          # Enable for detailed logging
          debug: false